"""Tests for the fleet (project-level) scripts.

Fixture = a synthetic 4-member project built in tmp_path:
    mini-a       converted service; imports mini_b; one import that near-misses mini-c
    mini-b       converted publisher (pyproject name mini-b, package mini_b);
                 catalog-info.yaml references mini-a
    mini-a-iac   unconverted IaC clone whose main.tf names mini-a
    mini-c       roster member with NO local clone

No network, no git binary dependence (freshness degrades to UNKNOWN by design
when git log fails -- asserted, not worked around).
"""
import json
import os
import subprocess
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
FLEET = os.path.dirname(HERE)
sys.path.insert(0, FLEET)

import fleetlib  # noqa: E402
from discover_members import catalog_fields, classify, glab, group_projects  # noqa: E402
from project_verify import binding_gaps  # noqa: E402


def run_script(name, *args):
    return subprocess.run(
        [sys.executable, os.path.join(FLEET, name)] + list(args),
        capture_output=True, text=True,
    )


# ------------------------------------------------------------------ fixture
def make_member(root, slug, converted=True, readme="Service does test things."):
    repo = root / slug
    (repo / ".git").mkdir(parents=True)          # classify() -> clone
    (repo / "README.md").write_text("# %s\n\n%s\n" % (slug, readme))
    if converted:
        (repo / "CLAUDE.md").write_text("# CLAUDE.md -- %s\n" % slug)
        kd = repo / "Knowledge"
        kd.mkdir()
        (kd / "KNOWLEDGE_GRAPH.md").write_text(
            "# %s Knowledge Graph\n\n**Purpose:** Navigation map for %s.\n\n"
            "**Last Updated:** Friday, August 15, 2026 (initial conversion)\n" % (slug, slug)
        )
    return repo


@pytest.fixture()
def project(tmp_path):
    a = make_member(tmp_path, "mini-a", readme="Service A does test things.")
    ka = a / "Knowledge"
    (ka / "CODE_INDEX.md").write_text(
        "# Knowledge/CODE_INDEX.md -- mini-a\n\n**Generated by:** test\n"
        "**Framework:** FastAPI\n**Derivation date:** Friday, August 15, 2026\n"
        "**Records:** 3\n"
    )
    (ka / "golden").mkdir()
    (ka / "golden" / "GOLDEN_FACTS.jsonl").write_text(
        '{"id": "GF-001", "path": "app.py", "line": 1, "expect": "GET /"}\n'
        '{"id": "GF-002", "path": "app.py", "line": 2, "expect": "GET /x"}\n'
    )
    ga = a / "Generated"
    (ga / "graphify").mkdir(parents=True)
    (ga / "READINESS_REPORT.md").write_text(
        "# Agent Readiness Report\n\n**Achieved level:** L2 -- Hygiene\n"
    )
    (ga / "CODE_INDEX_VALIDATION.md").write_text(
        "# VALIDATION_SUMMARY -- SME_CONTACTS.md\n\n## Results\n\n"
        "| Metric | Value |\n|--------|-------|\n"
        "| Total citations | 5 |\n| Resolved (pass) | 5 |\n"
        "| Verification rate | 100.0% |\n"
    )
    (ga / "graphify" / "CODE_GRAPH.jsonl").write_text(
        json.dumps({"path": "app.py", "line": 1, "kind": "dependency",
                    "identifier": "app.py -> os", "confidence": "EXTRACTED"}) + "\n" +
        json.dumps({"path": "app.py", "line": 2, "kind": "dependency",
                    "identifier": "app.py -> mini_b", "confidence": "EXTRACTED"}) + "\n" +
        json.dumps({"path": "app.py", "line": 3, "kind": "dependency",
                    "identifier": "app.py -> mini_c", "confidence": "EXTRACTED"}) + "\n"
    )

    b = make_member(tmp_path, "mini-b", readme="Publisher B library.")
    (b / "pyproject.toml").write_text('[project]\nname = "mini-b"\nversion = "0.1"\n')
    (b / "mini_b").mkdir()
    (b / "mini_b" / "__init__.py").write_text("")
    (b / "catalog-info.yaml").write_text(
        "apiVersion: backstage.io/v1alpha1\nspec:\n  dependsOn:\n    - mini-a\n"
    )

    iac = make_member(tmp_path, "mini-a-iac", converted=False, readme="IaC for A.")
    (iac / "main.tf").write_text('module "svc" {\n  name = "mini-a"\n}\n')

    proj = tmp_path / "proj"
    (proj / "Generated").mkdir(parents=True)
    (proj / "Generated" / "DRIFT.md").write_text("# DRIFT -- example/mini\n\ncontent\n")
    (proj / "MEMBERS.yaml").write_text(
        "# MEMBERS.yaml -- PROPOSED roster. Generated, not hand-edited.\n"
        "schema_version: 1\n"
        "project:\n"
        "  slug: miniproj\n"
        "  group: example/apps/mini\n"
        "  tracker: TST\n"
        '  measured_at: "2026-08-15 15:00"\n'
        "\n"
        "members:\n"
        "  - slug: mini-a\n"
        "    gitlab_path: example/apps/mini/mini-a\n"
        "    url: git@gitlab.com:example/apps/mini/mini-a.git\n"
        "    policy: observe\n"
        "    kind: clone\n"
        "    default_branch: main\n"
        "    last_activity: 2026-08-15\n"
        "    local_path: %s\n"
        "    converted: true\n"
        "\n"
        "  - slug: mini-b\n"
        "    gitlab_path: example/apps/mini/mini-b\n"
        "    url: git@gitlab.com:example/apps/mini/mini-b.git\n"
        "    policy: observe\n"
        "    kind: clone\n"
        "    default_branch: main\n"
        "    last_activity: 2026-08-14\n"
        "    local_path: %s\n"
        "    converted: true\n"
        "\n"
        "  - slug: mini-a-iac\n"
        "    gitlab_path: example/apps/mini/mini-a-iac\n"
        "    url: git@gitlab.com:example/apps/mini/mini-a-iac.git\n"
        "    policy: observe\n"
        "    kind: clone\n"
        "    default_branch: main\n"
        "    last_activity: 2026-08-13\n"
        "    local_path: %s\n"
        "\n"
        "  - slug: mini-c\n"
        "    gitlab_path: example/apps/mini/mini-c\n"
        "    url: git@gitlab.com:example/apps/mini/mini-c.git\n"
        "    policy: observe\n"
        "    kind: not-cloned\n"
        "    default_branch: main\n"
        "    last_activity: 2026-08-12\n"
        "\n" % (a, b, iac)
    )
    return proj


# ------------------------------------------------------------------ fleetlib
def test_parse_members_roundtrip(project):
    meta, members = fleetlib.parse_members(str(project / "MEMBERS.yaml"))
    assert meta["slug"] == "miniproj"
    assert meta["group"] == "example/apps/mini"
    assert meta["tracker"] == "TST"
    assert [m["slug"] for m in members] == ["mini-a", "mini-b", "mini-a-iac", "mini-c"]
    assert members[0]["converted"] == "true"
    assert members[3].get("local_path", "") == ""


def test_parse_members_missing_or_empty(tmp_path):
    with pytest.raises(ValueError):
        fleetlib.parse_members(str(tmp_path / "nope.yaml"))
    p = tmp_path / "MEMBERS.yaml"
    p.write_text("schema_version: 1\nproject:\n  slug: x\nmembers:\n")
    with pytest.raises(ValueError):
        fleetlib.parse_members(str(p))


def test_member_artifact_readers(project):
    meta, members = fleetlib.parse_members(str(project / "MEMBERS.yaml"))
    repo = members[0]["local_path"]
    assert fleetlib.is_converted(repo)
    assert fleetlib.read_code_index(repo)["records"] == 3
    assert fleetlib.read_code_index(repo)["framework"] == "FastAPI"
    assert fleetlib.read_golden_count(repo) == 2
    assert fleetlib.read_readiness_level(repo).startswith("L2")
    gate = fleetlib.read_gate(repo)
    assert gate["rate"] == 100.0 and gate["artifact"] == "SME_CONTACTS.md"
    assert fleetlib.code_graph_stats(repo)["edges"] == 3
    # .git is an empty dir, not a real repo: freshness must degrade to UNKNOWN, not crash
    assert fleetlib.freshness(repo) == "UNKNOWN"


def test_classify_kinds(tmp_path):
    clone = tmp_path / "c"; (clone / ".git").mkdir(parents=True)
    assert classify(str(clone)) == "clone"
    wt = tmp_path / "w"; wt.mkdir()
    (wt / ".git").write_text("gitdir: /x/.git/worktrees/w\n")
    assert classify(str(wt)) == "worktree"
    sm = tmp_path / "s"; sm.mkdir()
    (sm / ".git").write_text("gitdir: ../.git/modules/s\n")
    assert classify(str(sm)) == "submodule"
    plain = tmp_path / "p"; plain.mkdir()
    assert classify(str(plain)) == "not-a-repo"


def test_group_projects_pagination_and_dedup():
    pages = {
        1: [{"id": i} for i in range(100)],
        2: [{"id": 99}, {"id": 100}],   # overlap on 99 must dedup
    }

    def fetch(path):
        import re as _re
        page = int(_re.search(r"&page=(\d+)", path).group(1))
        return pages.get(page, [])

    got = group_projects("example%2Fgroup", fetch=fetch)
    assert len(got) == 101
    assert len({p["id"] for p in got}) == 101


# ------------------------------------------------------------------ builders
def test_registry_rows_and_values(project):
    r = run_script("build_fleet_registry.py", "--project-dir", str(project))
    assert r.returncode == 0, r.stderr
    rows = [json.loads(l) for l in
            open(project / "Generated" / "FLEET_REGISTRY.jsonl") if l.strip()]
    assert len(rows) == 4
    by = {r["slug"]: r for r in rows}
    a = by["mini-a"]
    assert a["converted"] is True
    assert a["code_index_records"] == 3
    assert a["golden_facts"] == 2
    assert a["graph_edges"] == 3
    assert a["gate_rate"] == 100.0
    assert a["gate_scope"] == "SME_CONTACTS.md"
    assert a["readiness"].startswith("L2")
    assert by["mini-a-iac"]["converted"] is False
    assert by["mini-c"]["local_path"] == ""
    md = open(project / "Generated" / "FLEET_REGISTRY.md").read()
    assert "100.0% (SME_CONTACTS.md)" in md          # gate scope stated, not implied
    assert "| mini-c | observe | none | no |" in md


def test_index_is_a_router_not_a_copy(project):
    run_script("build_fleet_registry.py", "--project-dir", str(project))
    r = run_script("build_project_index.py", "--project-dir", str(project))
    assert r.returncode == 0, r.stderr
    text = open(project / "PROJECT_INDEX.md").read()
    for slug in ("mini-a", "mini-b", "mini-a-iac", "mini-c"):
        assert slug in text
    assert "Service A does test things." in text          # README first prose line
    assert text.count("-> `") >= 4                        # pointer per member
    assert "Navigation map for mini-a" not in text        # KG content NOT inlined
    assert "## Converted members -- 2" in text


def test_cross_repo_edges(project):
    r = run_script("build_cross_repo_graph.py", "--project-dir", str(project))
    assert r.returncode == 0, r.stderr
    edges = [json.loads(l) for l in
             open(project / "Generated" / "CROSS_REPO_GRAPH.jsonl") if l.strip()]
    key = {(e["source"], e["target"], e["kind"]) for e in edges}

    # R1: engine-evidenced import edge with file:line from the record
    imp = [e for e in edges if e["kind"] == "imports"]
    assert ("mini-a", "mini-b", "imports") in key
    assert imp[0]["confidence"] == "EXTRACTED"
    assert imp[0]["evidence_path"] == "app.py" and imp[0]["evidence_line"] == 2

    # R2: iac pair, upgraded to tf evidence
    dep = [e for e in edges if e["kind"] == "deploys"][0]
    assert (dep["source"], dep["target"]) == ("mini-a-iac", "mini-a")
    assert dep["evidence_path"] == "main.tf" and dep["evidence_line"] == 2

    # R3: catalog reference
    assert ("mini-b", "mini-a", "references") in key

    # no self-edges, no stdlib-derived edges
    assert all(e["source"] != e["target"] for e in edges)
    assert ("mini-a", "mini-c", "imports") not in key     # near-miss goes to sidecar

    side = [json.loads(l) for l in
            open(project / "Generated" / "CROSS_REPO_NEEDS_VERIFICATION.jsonl") if l.strip()]
    assert len(side) == 1
    assert side[0]["candidate_target"] == "mini-c"
    assert side[0]["evidence_line"] == 3

    mmap = open(project / "Generated" / "ARCHITECTURE_MAP.md").read()
    assert "```mermaid" in mmap and "Scope honesty" in mmap


def test_verify_gate_pass_then_fail(project):
    for s in ("build_fleet_registry.py", "build_project_index.py", "build_cross_repo_graph.py"):
        assert run_script(s, "--project-dir", str(project)).returncode == 0
    ok = run_script("project_verify.py", str(project), "--no-shell")
    assert ok.returncode == 0, ok.stdout + ok.stderr
    assert "ALL CHECKS PASS" in ok.stdout

    os.remove(project / "PROJECT_INDEX.md")
    bad = run_script("project_verify.py", str(project), "--no-shell")
    assert bad.returncode == 1
    assert "R4 PROJECT_INDEX.md" in bad.stdout and "FAIL" in bad.stdout


# ------------------------------------------------------------- remote cache
def make_cache_member(project, slug, head_date="2026-08-16"):
    """Simulate fetch_member_artifacts.py output for an uncloned, converted member."""
    c = project / "Generated" / "remote_cache" / slug
    (c / "Knowledge").mkdir(parents=True)
    (c / "CLAUDE.md").write_text("# CLAUDE.md -- %s\n" % slug)
    (c / "README.md").write_text("# %s\n\nRemote service C does remote things.\n" % slug)
    (c / "Knowledge" / "KNOWLEDGE_GRAPH.md").write_text(
        "# %s Knowledge Graph\n\n**Purpose:** Navigation map for %s.\n\n"
        "**Last Updated:** Friday, August 15, 2026 (initial conversion)\n" % (slug, slug)
    )
    (c / "_meta.json").write_text(json.dumps({
        "slug": slug, "sha": "abcdef1234567890", "branch": "main",
        "head_committed_date": head_date, "fetched_at": "2026-08-16 10:00",
        "files": {"CLAUDE.md": "ok"},
    }))
    return c


def test_member_root_resolution(project, tmp_path):
    _, members = fleetlib.parse_members(str(project / "MEMBERS.yaml"))
    by = {m["slug"]: m for m in members}
    root, source = fleetlib.member_root(by["mini-a"], str(project))
    assert source == "local" and root == by["mini-a"]["local_path"]
    root, source = fleetlib.member_root(by["mini-c"], str(project))
    assert source == "none" and root == ""
    make_cache_member(project, "mini-c")
    root, source = fleetlib.member_root(by["mini-c"], str(project))
    assert source == "cache" and root.endswith("remote_cache/mini-c")
    # local always wins over cache
    make_cache_member(project, "mini-a")
    root, source = fleetlib.member_root(by["mini-a"], str(project))
    assert source == "local"


def test_registry_measures_cache_member(project):
    make_cache_member(project, "mini-c", head_date="2026-08-16")  # git moved past KG date
    r = run_script("build_fleet_registry.py", "--project-dir", str(project))
    assert r.returncode == 0, r.stderr
    rows = {x["slug"]: x for x in
            (json.loads(l) for l in open(project / "Generated" / "FLEET_REGISTRY.jsonl") if l.strip())}
    c = rows["mini-c"]
    assert c["source"] == "cache"
    assert c["converted"] is True
    assert c["freshness"] == "STALE"              # head 08-16 > KG 08-15, from _meta.json
    assert "(cache)" in c["last_commit"]
    run_script("build_project_index.py", "--project-dir", str(project))
    text = open(project / "PROJECT_INDEX.md").read()
    assert "Remote service C does remote things." in text
    assert "remote_cache/mini-c" in text and "(remote cache)" in text


def test_fetch_member_with_stubs(tmp_path):
    from fetch_member_artifacts import fetch_member

    content = {
        "CLAUDE.md": "# CLAUDE\n",
        "Knowledge/KNOWLEDGE_GRAPH.md": "# KG\n**Last Updated:** 2026-08-15\n",
    }
    calls = {"head": 0, "raw": 0}

    def head_fn(gp, branch):
        calls["head"] += 1
        return "sha1234567", "2026-08-15", None

    def raw_fn(gp, rel, ref):
        calls["raw"] += 1
        assert ref == "sha1234567"                 # fetch pinned to the head SHA
        if rel in content:
            return content[rel], "ok"
        return None, "absent"

    member = {"slug": "m1", "gitlab_path": "g/m1", "default_branch": "main"}
    cache = str(tmp_path / "cache")
    r = fetch_member(member, cache, head_fn=head_fn, raw_fn=raw_fn)
    assert r["status"] == "fetched" and r["ok"] == 2 and r["errors"] == 0
    meta = json.load(open(os.path.join(cache, "m1", "_meta.json")))
    assert meta["sha"] == "sha1234567"
    assert meta["files"]["CLAUDE.md"] == "ok"
    assert meta["files"]["AGENTS.md"] == "absent"  # absence recorded, not guessed
    assert open(os.path.join(cache, "m1", "CLAUDE.md")).read() == "# CLAUDE\n"

    # unchanged SHA -> skipped without any raw fetches
    before = calls["raw"]
    r2 = fetch_member(member, cache, head_fn=head_fn, raw_fn=raw_fn)
    assert r2["status"] == "current" and calls["raw"] == before

    # head error -> UNVERIFIED, cache untouched
    def head_err(gp, branch):
        return None, None, "500 boom"
    r3 = fetch_member(member, cache, head_fn=head_err, raw_fn=raw_fn)
    assert r3["status"] == "UNVERIFIED"
    assert os.path.isfile(os.path.join(cache, "m1", "CLAUDE.md"))


COMPLETE_BINDING = (
    "jira_project: TST\n"
    "epic: TST-1234\n"
    "board: 42\n"
    "dev_classification: Growth\n"
    'assignee_account_id: "0000aaaa1111bbbb2222cccc"\n'
)


def test_cache_blind_columns_are_not_reported_as_absent(project):
    """`readiness` and `graph edges` come from artifacts the converter git-ignores in
    the target repo, so a default-branch replica structurally cannot carry them.
    Rendering them as `--` next to genuinely-absent artifacts read as "this repo has
    none" -- and the Maestro lane makes cache the primary source, so that was most rows."""
    make_cache_member(project, "mini-c")
    assert run_script("build_fleet_registry.py", "--project-dir", str(project)).returncode == 0
    md = open(project / "Generated" / "FLEET_REGISTRY.md").read()
    row = [l for l in md.splitlines() if l.startswith("| mini-c |")][0]
    assert "| cache |" in row and "n/a*" in row
    assert "| mini-a |" in md and "n/a*" not in [l for l in md.splitlines()
                                                 if l.startswith("| mini-a |")][0]
    assert "this SOURCE cannot see it" in md          # the legend explains the cell

    # the router must make the same distinction -- it renders the same measurement
    assert run_script("build_project_index.py", "--project-dir", str(project)).returncode == 0
    idx = open(project / "PROJECT_INDEX.md").read()
    c_line = [l for l in idx.splitlines() if l.startswith("- **mini-c**")][0]
    assert "[n/a*]" in c_line, "a cache row's readiness is unmeasurable, not absent"
    a_line = [l for l in idx.splitlines() if l.startswith("- **mini-a**")][0]
    assert "[L2]" in a_line                            # local clone still reports its level
    assert "this source cannot see it" in idx          # legend carries the distinction


def test_unfetchable_artifacts_are_not_requested(tmp_path):
    """Every ARTIFACTS entry must be able to exist on a default branch. Two used to
    be git-ignored by the converter, so each cost a guaranteed 404 per member per run."""
    import fetch_member_artifacts as fma
    for gitignored in ("Generated/READINESS_REPORT.md",
                       "Generated/graphify/CODE_GRAPH.jsonl",
                       "Generated/Analysis/CODE_GRAPH.jsonl"):
        assert gitignored not in fma.ARTIFACTS, (
            "%s is git-ignored in the target repo by the converter -- fetching it can "
            "only ever 404" % gitignored)
    assert "Knowledge/KNOWLEDGE_GRAPH.md" in fma.ARTIFACTS


def test_api_errors_leave_the_previous_cache_intact(tmp_path):
    """The module docstring promises a non-404 error 'leaves any previous cache
    intact'. Deleting 404'd files inline broke that: a run whose first artifacts were
    absent and whose rest errored unlinked cached files, then returned UNVERIFIED
    without rewriting _meta.json -- metadata saying `ok` beside files that were gone."""
    from fetch_member_artifacts import fetch_member

    member = {"slug": "m1", "gitlab_path": "g/m1", "default_branch": "main"}
    cache = str(tmp_path / "cache")

    def head_fn(gp, branch):
        return "sha1", "2026-08-15", None

    def raw_ok(gp, rel, ref):
        return "# %s\n" % rel, "ok"

    assert fetch_member(member, cache, head_fn=head_fn, raw_fn=raw_ok)["status"] == "fetched"
    cached = os.path.join(cache, "m1", "CLAUDE.md")
    assert os.path.isfile(cached)

    # next run: CLAUDE.md now 404s, everything after it errors -> nothing fetched
    def raw_absent_then_error(gp, rel, ref):
        return (None, "absent") if rel == "CLAUDE.md" else (None, "error")

    r = fetch_member(member, cache, force=True,
                     head_fn=head_fn, raw_fn=raw_absent_then_error)
    assert r["status"] == "UNVERIFIED"
    assert os.path.isfile(cached), "an UNVERIFIED run must not mutate the cache"
    meta = json.load(open(os.path.join(cache, "m1", "_meta.json")))
    assert meta["files"]["CLAUDE.md"] == "ok", "metadata must still describe what is on disk"

    # a run that DOES fetch still prunes an upstream-deleted artifact
    def raw_absent_then_ok(gp, rel, ref):
        return (None, "absent") if rel == "CLAUDE.md" else ("# %s\n" % rel, "ok")

    r = fetch_member(member, cache, force=True,
                     head_fn=head_fn, raw_fn=raw_absent_then_ok)
    assert r["status"] == "fetched"
    assert not os.path.isfile(cached), "an artifact deleted upstream must leave the cache"


def test_verify_requires_binding_when_asked(project):
    for s in ("build_fleet_registry.py", "build_project_index.py", "build_cross_repo_graph.py"):
        run_script(s, "--project-dir", str(project))
    r = run_script("project_verify.py", str(project), "--no-shell", "--require-binding")
    assert r.returncode == 1 and "R7 BINDING.yml" in r.stdout
    (project / "BINDING.yml").write_text(COMPLETE_BINDING)
    r = run_script("project_verify.py", str(project), "--no-shell", "--require-binding")
    assert r.returncode == 0, r.stdout


def test_verify_rejects_a_binding_left_on_todo(project):
    """Phase 5 writes unevidenced fields as literal `TODO:` lines ON PURPOSE, so an
    existence-only R7 reported ALL CHECKS PASS on a binding no ticket can be cut
    from -- and /start-sdlc-feature then created one against `parent: TODO`."""
    for s in ("build_fleet_registry.py", "build_project_index.py", "build_cross_repo_graph.py"):
        run_script(s, "--project-dir", str(project))
    (project / "BINDING.yml").write_text(
        "jira_project: TST\n"
        'epic: "TODO: no epic in catalog-info.yaml and no sibling BINDING.yml found"\n'
        "board: TODO\n"
        "dev_classification: Growth\n"
        "assignee_account_id: TODO\n"
    )
    r = run_script("project_verify.py", str(project), "--no-shell", "--require-binding")
    assert r.returncode == 1, r.stdout
    assert "R7 BINDING.yml" in r.stdout and "TODO" in r.stdout
    for field in ("epic", "board", "assignee_account_id"):
        assert field in r.stdout
    assert "dev_classification" not in r.stdout.split("R7 BINDING.yml")[1].splitlines()[0]


def test_binding_gaps_separates_absent_from_todo(tmp_path):
    p = tmp_path / "BINDING.yml"
    # `board:` is deliberately NOT the last line: with a plain `\s*` after the colon
    # the regex backtracks over the newline and captures `dev_classification: Growth`,
    # so an empty value reads as filled everywhere except the end of the file -- which
    # is the one position a careless fixture puts it in.
    p.write_text("jira_project: TST\nepic: TODO\nboard:\ndev_classification: Growth\n")
    todo, missing = binding_gaps(str(p))
    assert set(todo) == {"epic", "board"}                       # empty value == unfilled
    assert set(missing) == {"assignee_account_id"}

    # every ordering of the empty field: first, middle, last
    for text, expect_empty in (
        ("epic:\njira_project: TST\nboard: 42\n"
         "dev_classification: Growth\nassignee_account_id: a\n", "epic"),
        ("jira_project: TST\nepic: TST-1\nboard:\n"
         "dev_classification: Growth\nassignee_account_id: a\n", "board"),
        ("jira_project: TST\nepic: TST-1\nboard: 42\n"
         "dev_classification: Growth\nassignee_account_id:\n", "assignee_account_id"),
    ):
        q = tmp_path / "b2.yml"
        q.write_text(text)
        todo, missing = binding_gaps(str(q))
        assert todo == [expect_empty], (text, todo, missing)
        assert missing == []
    p.write_text(COMPLETE_BINDING)
    assert binding_gaps(str(p)) == ([], [])
    assert binding_gaps(str(tmp_path / "nope.yml")) == ([], list(
        __import__("project_verify").BINDING_FIELDS))


def test_verify_reports_one_row_per_check_on_a_malformed_graph(project):
    for s in ("build_fleet_registry.py", "build_project_index.py", "build_cross_repo_graph.py"):
        run_script(s, "--project-dir", str(project))
    (project / "Generated" / "CROSS_REPO_GRAPH.jsonl").write_text("{not json}\n")
    r = run_script("project_verify.py", str(project), "--no-shell")
    assert r.returncode == 1
    rows = [l for l in r.stdout.splitlines() if "R5 cross-repo graph" in l]
    assert len(rows) == 1, "a FAIL row followed by a PASS row for the same check reads as passing"
    assert "FAIL" in rows[0] and "MALFORMED" in rows[0]


# ----------------------------------------------------------- catalog-info
def test_catalog_info_is_read_as_text_not_json():
    """The `/raw` file endpoint returns the file's bytes. Routing catalog-info.yaml
    through the JSON decoder returned None for every repo, so `role` and
    `owning_manager` were permanently empty while the agent prompt told a human to
    build the Phase 2 policy table and Phase 5 TEAM.md out of them."""
    raw = ("apiVersion: backstage.io/v1alpha1\nkind: Component\n"
           "metadata:\n  name: svc\nspec:\n  type: service\n"
           "  owningManager: someone@example.com\n")
    assert catalog_fields(raw) == ("service", "someone@example.com")
    # the regression, pinned: the JSON path cannot represent this file at all
    with pytest.raises(ValueError):
        json.loads(raw)
    assert catalog_fields("") == ("", "")
    assert catalog_fields("kind: Component\n") == ("", "")
    # a nested lookalike key must not answer for spec.type
    assert catalog_fields("spec:\n  mediaType: application/json\n")[0] == ""
    assert glab is not None  # imported to document that the JSON decoder still exists
