#!/usr/bin/env python3
"""propose_codeowners.py — evidence-derived CODEOWNERS draft, never authority.

Writes CODEOWNERS.proposed at the repo root: top recent committers overall plus
per-directory rules where a directory's ownership evidence differs. The file is
a PROPOSAL by construction — CODEOWNERS drives GitLab approval rules, and a
converter that commits one is granting review authority nobody consented to
(same sin class as inventing an endpoint). The owning team reviews, renames to
CODEOWNERS, and commits; that single rename is what flips the L2 readiness
criterion.

Evidence rules:
    - Recent window (default 400 commits) over full history: review authority
      should reflect who works here NOW, not 2019's top committer.
    - Bot filter: builtin list + .agentic/bots.txt (same contract as the SME
      derivation in the onboarding template).
    - Owners are EMAILS, verbatim from git identities — valid CODEOWNERS syntax
      in GitLab, and honest: mapping emails to @usernames would be guessing.
    - Per-directory rules only for first-level dirs with >= MIN_DIR_COMMITS in
      the window AND a top committer different from the root rule's first owner
      (a rule that repeats the root adds noise, not information).

UPDATE-safe: a real CODEOWNERS anywhere in the four conventional locations
means the repo is already governed — exit 0, write nothing, say so. An existing
.proposed is regenerated (it is a derived draft; the reviewed copy is the one
the team renamed).

Exit: 0 written or already-governed; 3 unusable (not a git repo / no
non-bot history — the reason on stderr).
"""
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

WINDOW = 400
TOP_OWNERS = 3
MIN_DIR_COMMITS = 20
GOVERNED = ("CODEOWNERS", ".gitlab/CODEOWNERS", ".github/CODEOWNERS",
            "docs/CODEOWNERS")
BUILTIN_BOTS = {"renovate", "renovate-bot", "dependabot", "dependabot[bot]",
                "ci-user", "gitlab-ci-token", "jenkins", "github-actions",
                "semantic-release-bot", "svc-automation"}


def bot_names(repo):
    bots = set(BUILTIN_BOTS)
    extra = repo / ".agentic" / "bots.txt"
    if extra.is_file():
        bots.update(l.strip().lower() for l in extra.read_text().splitlines()
                    if l.strip() and not l.startswith("#"))
    return bots


def is_bot(name, email, bots):
    ident = ("%s %s" % (name, email)).lower()
    return any(b in ident for b in bots) or "nobody@nowhere" in email


def recent_commits(repo):
    """[(email, name, [paths])] for the recent window, newest first."""
    out = subprocess.run(
        ["git", "-C", str(repo), "log", "-n", str(WINDOW),
         "--no-merges", "--name-only", "--format=%x1e%ae%x1f%an"],
        capture_output=True, text=True)
    if out.returncode != 0:
        return None
    commits = []
    for block in out.stdout.split("\x1e"):
        block = block.strip()
        if not block:
            continue
        head, _, body = block.partition("\n")
        email, _, name = head.partition("\x1f")
        paths = [l.strip() for l in body.splitlines() if l.strip()]
        commits.append((email.strip().lower(), name.strip(), paths))
    return commits


def main():
    if len(sys.argv) != 2:
        print("usage: propose_codeowners.py <repo_path>", file=sys.stderr)
        return 3
    repo = Path(sys.argv[1]).resolve()
    for g in GOVERNED:
        if (repo / g).is_file():
            print("[propose_codeowners] %s exists — repo already governed, "
                  "nothing to propose" % g)
            return 0
    commits = recent_commits(repo)
    if commits is None:
        print("[propose_codeowners] not a git repo (or git log failed): %s"
              % repo, file=sys.stderr)
        return 3
    bots = bot_names(repo)
    human = [(e, n, ps) for e, n, ps in commits if not is_bot(n, e, bots)]
    if not human:
        print("[propose_codeowners] no non-bot commits in the last %d — "
              "cannot derive ownership evidence" % WINDOW, file=sys.stderr)
        return 3

    overall = Counter(e for e, _, _ in human)
    root_owners = [e for e, _ in overall.most_common(TOP_OWNERS)]

    per_dir = {}
    for email, _, paths in human:
        for d in {p.split("/", 1)[0] for p in paths if "/" in p}:
            per_dir.setdefault(d, Counter())[email] += 1
    dir_rules = []
    for d in sorted(per_dir):
        counts = per_dir[d]
        if sum(counts.values()) < MIN_DIR_COMMITS or d.startswith("."):
            continue
        top = counts.most_common(1)[0][0]
        if top != root_owners[0]:
            dir_rules.append(("/%s/" % d, [top]))

    window_used = len(commits)
    lines = [
        "# CODEOWNERS.proposed — DERIVED DRAFT, not yet authority.",
        "#",
        "# Generated by the Agentic-Repos converter from git evidence: the most",
        "# recent %d commits (%d after bot filtering). CODEOWNERS drives GitLab"
        % (window_used, len(human)),
        "# approval rules, so the converter will NOT commit one on your behalf:",
        "# review these rules, adjust, RENAME this file to CODEOWNERS, and commit.",
        "# That rename is also what flips the L2 readiness criterion.",
        "#",
        "# Owners are the git identity emails, verbatim (valid GitLab CODEOWNERS",
        "# syntax). Regenerated on conversion re-runs — the reviewed copy is the",
        "# one you renamed.",
        "",
        "* %s" % " ".join(root_owners),
    ]
    if dir_rules:
        lines += ["", "# Directories whose recent evidence names a different "
                      "primary owner:"]
        lines += ["%s %s" % (path, " ".join(owners)) for path, owners in dir_rules]
    (repo / "CODEOWNERS.proposed").write_text("\n".join(lines) + "\n",
                                              encoding="utf-8")
    print("[propose_codeowners] wrote CODEOWNERS.proposed — root: %s%s"
          % (", ".join(root_owners),
             "; %d dir rule(s)" % len(dir_rules) if dir_rules else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
